@baseURL = https://vinicius.pro.br/daoo/rest/index.php

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsInVzZXIiOiJhZG0iLCJhZG1pbiI6IjEifQ.svD-VSvlCXzjxcJoR3yJ2MMiPZzFBUwatRJYrjZBTbg


# Contact
# Create
POST {{baseURL}}/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Angst",
  "email": "mbcangst2@gmail.com",
  "message": "mbcangst2@gmail.com",
  "description": "mbcangst2@gmail.com",
}
###

# Create
GET {{baseURL}}/contacts/view HTTP/1.1
Content-Type: text/html; charset=utf-8

###

# Pages
# Show All
GET {{baseURL}}/pages HTTP/1.1
Content-Type: text/html; charset=utf-8

###
# Pages
# Show
GET {{baseURL}}/pages/1 HTTP/1.1
Content-Type: text/html; charset=utf-8

###

###
# Clients
# Show
GET {{baseURL}}/clients HTTP/1.1
Content-Type: text/html; charset=utf-8
Authorization: {{token}}

###